### PR TITLE
Terminal fixes + enhancements

### PR DESCRIPTION
**Pull request by Yefancy**
Fixes and enhancements mentioned in #158

### CODE REVIEW

**Comment by ALongStringOfNumbers** [comment]
Some more things that I noticed after checking out the terminal after these updates.

The `file` and `url` theme options have a duplicate display for failed load:


----

For the Home button setting page, you can have multiple click action selection screens open at once, which causes the GUIs to overlap each other:


This is an example of just clicking on every click action box. I would suggest just limiting it to one selection gui open at once, and opening another one closes the currently open one.

----

When clicking on the battery manager app without a battery mounted, the following pop up dialog will appear



I would suggest changing this to say "Battery (any tier)" instead of "Battery (ULV)" as the latter makes it seem like only ULV batteries can be used.

-----

Mounting hardware still cannot pull items from your hotbar.

When attempting to mount hardware in the Hardware manager, items in the players hotbar are not displayed at all, just items in the non-hotbar inventory

----

The battery manager app does not update when the terminal is being charged by a battery in discharge mode.
- Mount an empty battery to the terminal
- Give yourself a full battery
- Enable discharge mode on the full battery
- See the terminal gaining charge
- Open up the terminal and see that the charge level in the Battery Manager app is not changing
- Close the terminal and see that the charge level has changed due to the discharged battery

----

Clarification in Battery Manager app:

Could we get this hover tooltip adjusted to say `Appname: Usage x EU/s`


Also, could we get a section displaying the total EU/s usage combined from all apps?

----

Unmounting a battery removes stored charge if it was charged via another battery in discharge mode

- Mount an empty battery
- Charge it fully with another battery in discharge mode
- Un-mount the battery
- See that the battery is now empty

----

Incorrect EU in mounted batteries.

I mounted a battery holding 14,800,512 EU, however the terminal displayed that it had half of that value, 7,400,256.

This was the NBT on the terminal, showing that the battery had double the charge than reported by the terminal
```less
<gregtech:meta_item_1:467>.withTag({terminal: {_hw: {battery: {item: {id: "gregtech:meta_item_1", Count: 1 as byte, tag: {Charge: 14800512 as long, DischargeMode: 1 as byte}, Damage: 742 as short}, charge: 7400256 as long, tier: 4, maxCharge: 16000000 as long}}}})
```

----

I can have multiple cursor displays in the `args` section of the Home Button Settings

I would expect the cursor mark to be cleared from a box when selecting another box.

This only happens when clicking on the boxes from top to bottom. If you have all boxes full of cursor lines like in the displayed picture above, clicking on a box again will remove cursor lines from all boxes after the box you clicked on.

----

Would it be possible to get some hovering information on the three column header on the Home Button settings page? I was really not sure what `args` could be used for, so some clarification helpers might be nice there.

----

In the App Store, having dark mode disabled simply displays a white background, while turning on dark mode displays the actual background image. Not sure if this is intended or not.

Non-dark mode:


Dark mode:


----

The Dark mode changes in the app store are saved when you exit the terminal with the Escape button, but not when you close the terminal by pressing the `e` button. Not sure if there is anything that can be done about this.

Speaking of dark mode, could the informational hover over the dark mode button in the app store change between displaying "dark mode" and "light mode" based on which mode you are currently on? Currently it just displays "dark mode" all the time.

----

After installing an App from the App Store, the button to open up the page still says "Install" instead of "Latest" like all other installed apps, until the terminal is restarted by closing through the escape button and re-opening it.

----

The store page for an app is not closed upon using the Home button to exit the app store. I have double click on the home button set to close apps, and when using this functionality in the app store with an app page open, only the app store is closed, leaving the app page open. This results in this, where the app page is open, but you are on the terminal menu:



----

Opening an app page in the app store and rapidly clicking on the `-` button in the top right causes the closing animation to rapidly repeat, causing the page to flash at the player. Note, you can click on the button even while the page is minimizing. It might make sense to block button interaction while the page is playing its close animation.

Doing this also causes this error to spam the log: https://pastebin.com/UcjPKdH0

----

The description of the World Prospector app has an extraneous `\n`


----

I encountered a crash when using the Recipe Chart app. I added an empty root slot to the page, and then opened up the calculate dialog, and pressed the confirm button while keeping the calculate dialog empty. Crash Report: https://pastebin.com/Twg2z55Z

----

You cannot use the recipe chart app when you are in JEI cheat mode, as clicking on an item from JEI to drag to the slot will simply add the item to your inventory. Not sure if there is anything you can do about this one.

----

The "Double Check" OS Setting is not saved when closing and relaunching the game.

----

These are the things that I have encountered so far.

**Comment by Yefancy** [comment]
> Some more things that I noticed after checking out the terminal after these updates.
> 
> The `file` and `url` theme options have a duplicate display for failed load:
Yes, they are. Same error tips, a small window preview.

> Also, could we get a section displaying the total EU/s usage combined from all apps?

Energy is consumed only when the application is open (or running in the background), so this may not important.

> Would it be possible to get some hovering information on the three column header on the Home Button settings page? I was really not sure what `args` could be used for, so some clarification helpers might be nice there.

will add a guid page for wiki in the future.

> Opening an app page in the app store and rapidly clicking on the `-` button in the top right causes the closing animation to rapidly repeat, causing the page to flash at the player. Note, you can click on the button even while the page is minimizing. It might make sense to block button interaction while the page is playing its close animation.
> 
> Doing this also causes this error to spam the log: https://pastebin.com/UcjPKdH0

Although I know the cause of the error, it is difficult to fix simply by changing a few lines of code. But it doesn't affect the game, so I'll leave it there

thanks for reviews.

**Comment by ALongStringOfNumbers** [comment]
A couple more things that I have noticed after checking out the recent changes:

----

When the terminal is in `maximize` mode, the selectors in the `Machine Guides` and `Multiblock Guides` apps seem to take up much more of the space than is required. See this example screenshot


Selecting the machine does not really need as much room as it is allocated. This is on GUI scale Large.

----

For the `maximize` and `minimize` buttons in the home button menu, could they be changed to say `Maximize/Minimize terminal` and `Minimize App` respectively? I was expecting the `minimize` button to bring me out of the maximized terminal, but it did not and I had to click on the `maximize` button again to bring me out of the maximized terminal. So some clarification on these buttons could be useful.

----

Is there anyway we can cancel the itemstack update animation for the terminal while it is charging. Right now if you are charging the terminal, the update animation will constantly be played, where the terminal and player arm bobs up and down while the terminal is charging. This can lead to stuff like



Where the terminal is being held by the player, but is constantly off the screen due to the update animation being played while the terminal is charging

----

This one may be a bit difficult. Batteries change their texture based on the level of charge that they are holding, would it be possible to mimic this is the Hardware manager app? Right now the texture displayed is always the texture of the battery when it is inserted, not based on the current charge of the terminal. If this is too annoying, feel free to skip.

----

There is still some weirdness with terminals retaining charge/mis-representing charge.

I mounted a full MV sodium battery, which holds 360,000 EU. I then unmounted the battery and was returned a battery with a charge of 222,880 EU, while the terminal kept a charge of 180,000 EU.

First of all, I would expect the battery to take all the charge, and secondly, these numbers do not add up to the 360,000 EU charge capacity of the battery.



Here is a screenshot of the battery and the terminal after dismounting the battery, and here is the nbt of the terminal:
```less
<gregtech:meta_item_1:467>.withTag({terminal: {_installed: ["recipe_chart"], recipe_chart: {_tier: 3}, _hw: {}}})
```
The lapotron battery in my inventory is in discharge mode, which might be behind some of the issues.


When I remounted the battery that had a charge of 222,880 EU into a fresh terminal, the charge level suddenly dropped to approximately 100,000 EU. So something weird is happening with the transfer of charge when mounting and dismounting batteries.

When I dismounted and remounted the battery again, it lost approximately 80,000 EU of charge.

This may have something to do with the fact that battery charge is not synced to terminal charge. In this grab of NBT from the terminal, you can see that the battery's NBT charge value is different from the terminal.
```less
<gregtech:meta_item_1:467>.withTag({terminal: {_hw: {battery: {item: {id: "gregtech:meta_item_1", Count: 1 as byte, tag: {Charge: 152912 as long}, Damage: 733 as short}, charge: 360000 as long, tier: 2, maxCharge: 360000 as long}}}})
```

----

The issue where the terminal displays half the charge of the battery seems to still exist. Here is a grab of NBT from a terminal where this is occurring:
```less
<gregtech:meta_item_1:467>.withTag({terminal: {_hw: {battery: {item: {id: "gregtech:meta_item_1", Count: 1 as byte, tag: {Charge: 15272104 as long, DischargeMode: 1 as byte}, Damage: 742 as short}, charge: 7636052 as long, tier: 4, maxCharge: 16000000 as long}}}})
```
This occurs regardless of whether the battery is in discharge mode or not, and I have had it happen with every full battery that I have pulled from the creative menu. This even happened with a full battery that I charged in a battery buffer and did not pull from the creative menu.

----

**Comment by Yefancy** [comment]
> When the terminal is in `maximize` mode, the selectors in the `Machine Guides` and `Multiblock Guides` apps seem to take up much more of the space than is required. See this example screenshot

The width of the page is fixed for now, and may be adapted later

**Comment by ALongStringOfNumbers** [comment]
> in additional, fix
> 
> > Opening an app page in the app store and rapidly clicking on the `-` button in the top right causes the closing animation to rapidly repeat, causing the page to flash at the player. Note, you can click on the button even while the page is minimizing. It might make sense to block button interaction while the page is playing its close animation.
> > Doing this also causes this error to spam the log: https://pastebin.com/UcjPKdH0

I still seem to be able to cause the error to appear in the log, but the page no longer flashes at the player. New log snippet: https://pastebin.com/fnrV1GEU

----

The last issue in #158, which I added a couple days ago, seems to still be present.

Also, did that popup dialog for running out of power while using an app ever get added?

**Review by TechLord22 — APPROVED** [review]

**Comment by Yefancy** [comment]
> I still seem to be able to cause the error to appear in the log, but the page no longer flashes at the player. New log snippet:

fixed



> Also, did that popup dialog for running out of power while using an app ever get added?

added



> The last issue in #158, which I added a couple days ago, seems to still be present.

The cost of perfect solutions is high, requiring a redesign of the drawing process for widgets

**Comment by Yefancy** [comment]
I don't want to do any more work in this PR for minor optimizations or experiences, unless there's a fatal bug, I think it's time to merge it. QoE improments can be the later thing

**Review by ALongStringOfNumbers — APPROVED** [review]

**Pull request merged**
